#!/usr/bin/awk -f
#
# gc - gemini-fy code
# public domain

/^\t/ {
	if (!pre) {
		pre = 1
		print "```"
	}
	emptylines()
	print substr($0, 2)
	next
}

/^$/ {
	if (pre)
		empty++
	else
		print $0
	next
}

// {
	if (pre) {
		pre = 0
		print "```"
	}
	emptylines()
	print $0
}

END { if (pre) print "```" }

function emptylines() {
	for (i = 0; i < empty; i++)
		print ""
	empty = 0
}
